development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: jobbee
  username: root
  password: 'Sm4rtt1m3'
  host: "localhost"

# test:
  # adapter: mysql2
  # encoding: utf8
  # reconnect: false
  # database: calpad
  # pool: 5
  # username: root
  # password: 'cong2004'
  # host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: captTest
  pool: 5
  username: root
  password: 'Sm4rtt1m3'
  host: localhost
